stages:
  - build

before_script:
  - git submodule init
  - git submodule update
  # Create python environment
  - test -f Miniconda3-latest-Linux-x86_64.sh || wget -nv http://anaconda.rdhpcs.noaa.gov/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p `pwd`/local_env
  - export PATH=`pwd`/local_env/bin:$PATH

# Test
build:
  stage: build
  tags:
    - pan
  script:
    - conda create -q -y -n py3 python=3.6 numpy netcdf4 numba scipy
    - . activate py3
    - conda list -e
    - make
